name: github-actions-cloud-run-jfrog

on: [push]

jobs:
  build:
    name: Build a Spring Boot app and Upload it to Artifactory (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Setup jfrog cli
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}

      - name: Maven Build & Deploy to Artifactory
        run: |
          ./mvnw -s settings.xml clean deploy
          
      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # - name: Configure Docker
      #   run: |
      #     gcloud auth configure-docker
      
      # - name: Build
      #   run: |
      #     docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-actions-cloud-run-jfrog:latest .

      # - name: Push
      #   run: |
      #     docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-actions-cloud-run-jfrog:latest

      # - name: Deploy
      #   run: |
      #     gcloud run deploy github-actions-cloud-run-jfrog \
      #     --region asia-northeast1 \
      #     --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-actions-cloud-run-jfrog \
      #     --platform managed \
      #     --allow-unauthenticated \
      #     --project ${{ secrets.GCP_PROJECT_ID }}