name: github-actions-cloud-run-jfrog

on: [push]

jobs:
  build:
    name: Build a Spring Boot app, a Docker image and upload them to Artifactory (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Setup jfrog cli
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_SECRET_1 }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Build & Deploy to Artifactory
        run: |
          ./mvnw -s settings.xml -DskipTests clean deploy
        env:
          JF_ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          JF_ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}

      - name: Docker Build & Deploy to Artifactory
        run: |
          echo ${{ secrets.ARTIFACTORY_PASS }} | docker login -u${{ secrets.ARTIFACTORY_USER }} --password-stdin kirasoa-cicd-docker-dev.jfrog.io
          docker build -t kirasoa-cicd-docker-dev.jfrog.io/github-actions-cloud-run-jfrog:latest .
          jfrog rt build-collect-env
          jfrog rt docker-push kirasoa-cicd-docker-dev.jfrog.io/github-actions-cloud-run-jfrog:latest
          jfrog rt build-publish

  deploy:
    name: Deploy the Docker image to GCP Cloud Run (CD)
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Word Around to work with Cloud Run (Fully Managed)
        run: |
          gcloud auth configure-docker
          docker pull kirasoa-cicd-docker-dev.jfrog.io/github-actions-cloud-run-jfrog:latest
          docker tag kirasoa-cicd-docker-dev.jfrog.io/github-actions-cloud-run-jfrog:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-actions-cloud-run-jfrog:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-actions-cloud-run-jfrog:latest

      - name: Deploy
        run: |
          gcloud run deploy github-actions-cloud-run-jfrog \
          --region asia-northeast1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-actions-cloud-run-jfrog:latest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
